version: '3.7'

services:
    imaginary:
      image: h2non/imaginary:latest
      # optionally mount a volume as local image source
      volumes:
        - ./images:/mnt/data
      environment:
        PORT: 9000
      command: -enable-url-source -mount /mnt/data
      ports:
        - "9000:9000"
    kafka:
      container_name: kafka
      image: 'bitnami/kafka:latest'
      environment:
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      ports:
        - '9092:9092'
        - '9093:9093'
        - '9094:9094'
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: 123456!
        POSTGRES_DB: imagix
      ports:
          - "5432:5432"