version: '3.7'

networks:
  netmain:
    driver: bridge

services:
    imaginary:
      image: h2non/imaginary:latest
      # optionally mount a volume as local image source
      volumes:
        - ./images:/mnt/data
      environment:
        PORT: 9000
      command: -enable-url-source -mount /mnt/data
      ports:
        - "9000:9000"
      networks:
        - netmain
    kafka:
      container_name: kafka
      image: 'bitnami/kafka:3.9'
      hostname: kafka
      environment:
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      ports:
        - '9092:9092'
        - '9093:9093'
        - '9094:9094'
      networks:
        - netmain
    mysql:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: 123456!
        MYSQL_DATABASE: smart_image
      ports:
        - "3306:3306"
      volumes:
        - ./mysql_data:/var/lib/mysql
      networks:
        - netmain

    kafka-ui:
      image: provectuslabs/kafka-ui
      container_name: kafka-ui
      depends_on:
        - kafka
      ports:
        - "8088:8080"
      restart: always
      environment:
        - KAFKA_CLUSTERS_0_NAME=kafka
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      networks:
        - netmain
    localstack:
      container_name: localstack
      networks:
        - netmain
      image: localstack/localstack
      ports:
        - "127.0.0.1:4566:4566"            # LocalStack Gateway
      environment:
        - DEBUG=${DEBUG:-0}
      volumes:
        - "./localstack:/var/lib/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"


