// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/smart-cms/service.proto

package smartcmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Banner struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SiteId           int32                  `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Title            *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Url              string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	BannerData       *string                `protobuf:"bytes,5,opt,name=banner_data,json=bannerData,proto3,oneof" json:"banner_data,omitempty"`
	Order            *int32                 `protobuf:"varint,6,opt,name=order,proto3,oneof" json:"order,omitempty"`
	Type             int32                  `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	StartDate        *string                `protobuf:"bytes,8,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate          *string                `protobuf:"bytes,9,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	ButtonText       *string                `protobuf:"bytes,10,opt,name=button_text,json=buttonText,proto3,oneof" json:"button_text,omitempty"`
	ButtonLink       *string                `protobuf:"bytes,11,opt,name=button_link,json=buttonLink,proto3,oneof" json:"button_link,omitempty"`
	IsActive         int32                  `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Image            *string                `protobuf:"bytes,13,opt,name=image,proto3,oneof" json:"image,omitempty"`
	MobileTitle      *string                `protobuf:"bytes,14,opt,name=mobile_title,json=mobileTitle,proto3,oneof" json:"mobile_title,omitempty"`
	MobileUrl        *string                `protobuf:"bytes,15,opt,name=mobile_url,json=mobileUrl,proto3,oneof" json:"mobile_url,omitempty"`
	MobileBannerData *string                `protobuf:"bytes,16,opt,name=mobile_banner_data,json=mobileBannerData,proto3,oneof" json:"mobile_banner_data,omitempty"`
	MobileOrder      *int32                 `protobuf:"varint,17,opt,name=mobile_order,json=mobileOrder,proto3,oneof" json:"mobile_order,omitempty"`
	MobileType       int32                  `protobuf:"varint,18,opt,name=mobile_type,json=mobileType,proto3" json:"mobile_type,omitempty"`
	MobileStartDate  *string                `protobuf:"bytes,19,opt,name=mobile_start_date,json=mobileStartDate,proto3,oneof" json:"mobile_start_date,omitempty"`
	MobileEndDate    *string                `protobuf:"bytes,20,opt,name=mobile_end_date,json=mobileEndDate,proto3,oneof" json:"mobile_end_date,omitempty"`
	MobileIsActive   int32                  `protobuf:"varint,21,opt,name=mobile_is_active,json=mobileIsActive,proto3" json:"mobile_is_active,omitempty"`
	MobileButtonText *string                `protobuf:"bytes,22,opt,name=mobile_button_text,json=mobileButtonText,proto3,oneof" json:"mobile_button_text,omitempty"`
	MobileButtonLink *string                `protobuf:"bytes,23,opt,name=mobile_button_link,json=mobileButtonLink,proto3,oneof" json:"mobile_button_link,omitempty"`
	MobileImage      *string                `protobuf:"bytes,24,opt,name=mobile_image,json=mobileImage,proto3,oneof" json:"mobile_image,omitempty"`
	SegmentId        int32                  `protobuf:"varint,25,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	SiteShowType     string                 `protobuf:"bytes,26,opt,name=site_show_type,json=siteShowType,proto3" json:"site_show_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Banner) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *Banner) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Banner) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Banner) GetBannerData() string {
	if x != nil && x.BannerData != nil {
		return *x.BannerData
	}
	return ""
}

func (x *Banner) GetOrder() int32 {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return 0
}

func (x *Banner) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Banner) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *Banner) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *Banner) GetButtonText() string {
	if x != nil && x.ButtonText != nil {
		return *x.ButtonText
	}
	return ""
}

func (x *Banner) GetButtonLink() string {
	if x != nil && x.ButtonLink != nil {
		return *x.ButtonLink
	}
	return ""
}

func (x *Banner) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

func (x *Banner) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *Banner) GetMobileTitle() string {
	if x != nil && x.MobileTitle != nil {
		return *x.MobileTitle
	}
	return ""
}

func (x *Banner) GetMobileUrl() string {
	if x != nil && x.MobileUrl != nil {
		return *x.MobileUrl
	}
	return ""
}

func (x *Banner) GetMobileBannerData() string {
	if x != nil && x.MobileBannerData != nil {
		return *x.MobileBannerData
	}
	return ""
}

func (x *Banner) GetMobileOrder() int32 {
	if x != nil && x.MobileOrder != nil {
		return *x.MobileOrder
	}
	return 0
}

func (x *Banner) GetMobileType() int32 {
	if x != nil {
		return x.MobileType
	}
	return 0
}

func (x *Banner) GetMobileStartDate() string {
	if x != nil && x.MobileStartDate != nil {
		return *x.MobileStartDate
	}
	return ""
}

func (x *Banner) GetMobileEndDate() string {
	if x != nil && x.MobileEndDate != nil {
		return *x.MobileEndDate
	}
	return ""
}

func (x *Banner) GetMobileIsActive() int32 {
	if x != nil {
		return x.MobileIsActive
	}
	return 0
}

func (x *Banner) GetMobileButtonText() string {
	if x != nil && x.MobileButtonText != nil {
		return *x.MobileButtonText
	}
	return ""
}

func (x *Banner) GetMobileButtonLink() string {
	if x != nil && x.MobileButtonLink != nil {
		return *x.MobileButtonLink
	}
	return ""
}

func (x *Banner) GetMobileImage() string {
	if x != nil && x.MobileImage != nil {
		return *x.MobileImage
	}
	return ""
}

func (x *Banner) GetSegmentId() int32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *Banner) GetSiteShowType() string {
	if x != nil {
		return x.SiteShowType
	}
	return ""
}

type BannerArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	IsActive      *int32                 `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	IsAutoslide   *int32                 `protobuf:"varint,5,opt,name=is_autoslide,json=isAutoslide,proto3,oneof" json:"is_autoslide,omitempty"`
	PositionId    *int32                 `protobuf:"varint,6,opt,name=position_id,json=positionId,proto3,oneof" json:"position_id,omitempty"`
	SlideSpeed    *int32                 `protobuf:"varint,7,opt,name=slide_speed,json=slideSpeed,proto3,oneof" json:"slide_speed,omitempty"`
	SiteId        int32                  `protobuf:"varint,8,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerArea) Reset() {
	*x = BannerArea{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerArea) ProtoMessage() {}

func (x *BannerArea) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerArea.ProtoReflect.Descriptor instead.
func (*BannerArea) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{1}
}

func (x *BannerArea) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BannerArea) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BannerArea) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BannerArea) GetIsActive() int32 {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return 0
}

func (x *BannerArea) GetIsAutoslide() int32 {
	if x != nil && x.IsAutoslide != nil {
		return *x.IsAutoslide
	}
	return 0
}

func (x *BannerArea) GetPositionId() int32 {
	if x != nil && x.PositionId != nil {
		return *x.PositionId
	}
	return 0
}

func (x *BannerArea) GetSlideSpeed() int32 {
	if x != nil && x.SlideSpeed != nil {
		return *x.SlideSpeed
	}
	return 0
}

func (x *BannerArea) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type GetAllBannersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBannersRequest) Reset() {
	*x = GetAllBannersRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBannersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBannersRequest) ProtoMessage() {}

func (x *GetAllBannersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBannersRequest.ProtoReflect.Descriptor instead.
func (*GetAllBannersRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{2}
}

type GetAllBannersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banners       []*Banner              `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBannersResponse) Reset() {
	*x = GetAllBannersResponse{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBannersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBannersResponse) ProtoMessage() {}

func (x *GetAllBannersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBannersResponse.ProtoReflect.Descriptor instead.
func (*GetAllBannersResponse) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllBannersResponse) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

type GetBannerByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBannerByIDRequest) Reset() {
	*x = GetBannerByIDRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBannerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannerByIDRequest) ProtoMessage() {}

func (x *GetBannerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannerByIDRequest.ProtoReflect.Descriptor instead.
func (*GetBannerByIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetBannerByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateBannerRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SiteId           int32                  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Title            *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Url              string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	BannerData       *string                `protobuf:"bytes,4,opt,name=banner_data,json=bannerData,proto3,oneof" json:"banner_data,omitempty"`
	Order            *int32                 `protobuf:"varint,5,opt,name=order,proto3,oneof" json:"order,omitempty"`
	Type             int32                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	StartDate        *string                `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate          *string                `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	ButtonText       *string                `protobuf:"bytes,9,opt,name=button_text,json=buttonText,proto3,oneof" json:"button_text,omitempty"`
	ButtonLink       *string                `protobuf:"bytes,10,opt,name=button_link,json=buttonLink,proto3,oneof" json:"button_link,omitempty"`
	IsActive         int32                  `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Image            *string                `protobuf:"bytes,12,opt,name=image,proto3,oneof" json:"image,omitempty"`
	MobileTitle      *string                `protobuf:"bytes,13,opt,name=mobile_title,json=mobileTitle,proto3,oneof" json:"mobile_title,omitempty"`
	MobileUrl        *string                `protobuf:"bytes,14,opt,name=mobile_url,json=mobileUrl,proto3,oneof" json:"mobile_url,omitempty"`
	MobileBannerData *string                `protobuf:"bytes,15,opt,name=mobile_banner_data,json=mobileBannerData,proto3,oneof" json:"mobile_banner_data,omitempty"`
	MobileOrder      *int32                 `protobuf:"varint,16,opt,name=mobile_order,json=mobileOrder,proto3,oneof" json:"mobile_order,omitempty"`
	MobileType       int32                  `protobuf:"varint,17,opt,name=mobile_type,json=mobileType,proto3" json:"mobile_type,omitempty"`
	MobileStartDate  *string                `protobuf:"bytes,18,opt,name=mobile_start_date,json=mobileStartDate,proto3,oneof" json:"mobile_start_date,omitempty"`
	MobileEndDate    *string                `protobuf:"bytes,19,opt,name=mobile_end_date,json=mobileEndDate,proto3,oneof" json:"mobile_end_date,omitempty"`
	MobileIsActive   int32                  `protobuf:"varint,20,opt,name=mobile_is_active,json=mobileIsActive,proto3" json:"mobile_is_active,omitempty"`
	MobileButtonText *string                `protobuf:"bytes,21,opt,name=mobile_button_text,json=mobileButtonText,proto3,oneof" json:"mobile_button_text,omitempty"`
	MobileButtonLink *string                `protobuf:"bytes,22,opt,name=mobile_button_link,json=mobileButtonLink,proto3,oneof" json:"mobile_button_link,omitempty"`
	MobileImage      *string                `protobuf:"bytes,23,opt,name=mobile_image,json=mobileImage,proto3,oneof" json:"mobile_image,omitempty"`
	SegmentId        int32                  `protobuf:"varint,24,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	SiteShowType     string                 `protobuf:"bytes,25,opt,name=site_show_type,json=siteShowType,proto3" json:"site_show_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateBannerRequest) Reset() {
	*x = CreateBannerRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBannerRequest) ProtoMessage() {}

func (x *CreateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBannerRequest.ProtoReflect.Descriptor instead.
func (*CreateBannerRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBannerRequest) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *CreateBannerRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *CreateBannerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateBannerRequest) GetBannerData() string {
	if x != nil && x.BannerData != nil {
		return *x.BannerData
	}
	return ""
}

func (x *CreateBannerRequest) GetOrder() int32 {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return 0
}

func (x *CreateBannerRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateBannerRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *CreateBannerRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *CreateBannerRequest) GetButtonText() string {
	if x != nil && x.ButtonText != nil {
		return *x.ButtonText
	}
	return ""
}

func (x *CreateBannerRequest) GetButtonLink() string {
	if x != nil && x.ButtonLink != nil {
		return *x.ButtonLink
	}
	return ""
}

func (x *CreateBannerRequest) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

func (x *CreateBannerRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *CreateBannerRequest) GetMobileTitle() string {
	if x != nil && x.MobileTitle != nil {
		return *x.MobileTitle
	}
	return ""
}

func (x *CreateBannerRequest) GetMobileUrl() string {
	if x != nil && x.MobileUrl != nil {
		return *x.MobileUrl
	}
	return ""
}

func (x *CreateBannerRequest) GetMobileBannerData() string {
	if x != nil && x.MobileBannerData != nil {
		return *x.MobileBannerData
	}
	return ""
}

func (x *CreateBannerRequest) GetMobileOrder() int32 {
	if x != nil && x.MobileOrder != nil {
		return *x.MobileOrder
	}
	return 0
}

func (x *CreateBannerRequest) GetMobileType() int32 {
	if x != nil {
		return x.MobileType
	}
	return 0
}

func (x *CreateBannerRequest) GetMobileStartDate() string {
	if x != nil && x.MobileStartDate != nil {
		return *x.MobileStartDate
	}
	return ""
}

func (x *CreateBannerRequest) GetMobileEndDate() string {
	if x != nil && x.MobileEndDate != nil {
		return *x.MobileEndDate
	}
	return ""
}

func (x *CreateBannerRequest) GetMobileIsActive() int32 {
	if x != nil {
		return x.MobileIsActive
	}
	return 0
}

func (x *CreateBannerRequest) GetMobileButtonText() string {
	if x != nil && x.MobileButtonText != nil {
		return *x.MobileButtonText
	}
	return ""
}

func (x *CreateBannerRequest) GetMobileButtonLink() string {
	if x != nil && x.MobileButtonLink != nil {
		return *x.MobileButtonLink
	}
	return ""
}

func (x *CreateBannerRequest) GetMobileImage() string {
	if x != nil && x.MobileImage != nil {
		return *x.MobileImage
	}
	return ""
}

func (x *CreateBannerRequest) GetSegmentId() int32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *CreateBannerRequest) GetSiteShowType() string {
	if x != nil {
		return x.SiteShowType
	}
	return ""
}

type UpdateBannerRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SiteId           int32                  `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Title            *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Url              string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	BannerData       *string                `protobuf:"bytes,5,opt,name=banner_data,json=bannerData,proto3,oneof" json:"banner_data,omitempty"`
	Order            *int32                 `protobuf:"varint,6,opt,name=order,proto3,oneof" json:"order,omitempty"`
	Type             int32                  `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	StartDate        *string                `protobuf:"bytes,8,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate          *string                `protobuf:"bytes,9,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	ButtonText       *string                `protobuf:"bytes,10,opt,name=button_text,json=buttonText,proto3,oneof" json:"button_text,omitempty"`
	ButtonLink       *string                `protobuf:"bytes,11,opt,name=button_link,json=buttonLink,proto3,oneof" json:"button_link,omitempty"`
	IsActive         int32                  `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Image            *string                `protobuf:"bytes,13,opt,name=image,proto3,oneof" json:"image,omitempty"`
	MobileTitle      *string                `protobuf:"bytes,14,opt,name=mobile_title,json=mobileTitle,proto3,oneof" json:"mobile_title,omitempty"`
	MobileUrl        *string                `protobuf:"bytes,15,opt,name=mobile_url,json=mobileUrl,proto3,oneof" json:"mobile_url,omitempty"`
	MobileBannerData *string                `protobuf:"bytes,16,opt,name=mobile_banner_data,json=mobileBannerData,proto3,oneof" json:"mobile_banner_data,omitempty"`
	MobileOrder      *int32                 `protobuf:"varint,17,opt,name=mobile_order,json=mobileOrder,proto3,oneof" json:"mobile_order,omitempty"`
	MobileType       int32                  `protobuf:"varint,18,opt,name=mobile_type,json=mobileType,proto3" json:"mobile_type,omitempty"`
	MobileStartDate  *string                `protobuf:"bytes,19,opt,name=mobile_start_date,json=mobileStartDate,proto3,oneof" json:"mobile_start_date,omitempty"`
	MobileEndDate    *string                `protobuf:"bytes,20,opt,name=mobile_end_date,json=mobileEndDate,proto3,oneof" json:"mobile_end_date,omitempty"`
	MobileIsActive   int32                  `protobuf:"varint,21,opt,name=mobile_is_active,json=mobileIsActive,proto3" json:"mobile_is_active,omitempty"`
	MobileButtonText *string                `protobuf:"bytes,22,opt,name=mobile_button_text,json=mobileButtonText,proto3,oneof" json:"mobile_button_text,omitempty"`
	MobileButtonLink *string                `protobuf:"bytes,23,opt,name=mobile_button_link,json=mobileButtonLink,proto3,oneof" json:"mobile_button_link,omitempty"`
	MobileImage      *string                `protobuf:"bytes,24,opt,name=mobile_image,json=mobileImage,proto3,oneof" json:"mobile_image,omitempty"`
	SegmentId        int32                  `protobuf:"varint,25,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	SiteShowType     string                 `protobuf:"bytes,26,opt,name=site_show_type,json=siteShowType,proto3" json:"site_show_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateBannerRequest) Reset() {
	*x = UpdateBannerRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBannerRequest) ProtoMessage() {}

func (x *UpdateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBannerRequest.ProtoReflect.Descriptor instead.
func (*UpdateBannerRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBannerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBannerRequest) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *UpdateBannerRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateBannerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateBannerRequest) GetBannerData() string {
	if x != nil && x.BannerData != nil {
		return *x.BannerData
	}
	return ""
}

func (x *UpdateBannerRequest) GetOrder() int32 {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return 0
}

func (x *UpdateBannerRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateBannerRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *UpdateBannerRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *UpdateBannerRequest) GetButtonText() string {
	if x != nil && x.ButtonText != nil {
		return *x.ButtonText
	}
	return ""
}

func (x *UpdateBannerRequest) GetButtonLink() string {
	if x != nil && x.ButtonLink != nil {
		return *x.ButtonLink
	}
	return ""
}

func (x *UpdateBannerRequest) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

func (x *UpdateBannerRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *UpdateBannerRequest) GetMobileTitle() string {
	if x != nil && x.MobileTitle != nil {
		return *x.MobileTitle
	}
	return ""
}

func (x *UpdateBannerRequest) GetMobileUrl() string {
	if x != nil && x.MobileUrl != nil {
		return *x.MobileUrl
	}
	return ""
}

func (x *UpdateBannerRequest) GetMobileBannerData() string {
	if x != nil && x.MobileBannerData != nil {
		return *x.MobileBannerData
	}
	return ""
}

func (x *UpdateBannerRequest) GetMobileOrder() int32 {
	if x != nil && x.MobileOrder != nil {
		return *x.MobileOrder
	}
	return 0
}

func (x *UpdateBannerRequest) GetMobileType() int32 {
	if x != nil {
		return x.MobileType
	}
	return 0
}

func (x *UpdateBannerRequest) GetMobileStartDate() string {
	if x != nil && x.MobileStartDate != nil {
		return *x.MobileStartDate
	}
	return ""
}

func (x *UpdateBannerRequest) GetMobileEndDate() string {
	if x != nil && x.MobileEndDate != nil {
		return *x.MobileEndDate
	}
	return ""
}

func (x *UpdateBannerRequest) GetMobileIsActive() int32 {
	if x != nil {
		return x.MobileIsActive
	}
	return 0
}

func (x *UpdateBannerRequest) GetMobileButtonText() string {
	if x != nil && x.MobileButtonText != nil {
		return *x.MobileButtonText
	}
	return ""
}

func (x *UpdateBannerRequest) GetMobileButtonLink() string {
	if x != nil && x.MobileButtonLink != nil {
		return *x.MobileButtonLink
	}
	return ""
}

func (x *UpdateBannerRequest) GetMobileImage() string {
	if x != nil && x.MobileImage != nil {
		return *x.MobileImage
	}
	return ""
}

func (x *UpdateBannerRequest) GetSegmentId() int32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *UpdateBannerRequest) GetSiteShowType() string {
	if x != nil {
		return x.SiteShowType
	}
	return ""
}

type DeleteBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBannerRequest) Reset() {
	*x = DeleteBannerRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerRequest) ProtoMessage() {}

func (x *DeleteBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBannerRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBannerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllBannerAreasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBannerAreasRequest) Reset() {
	*x = GetAllBannerAreasRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBannerAreasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBannerAreasRequest) ProtoMessage() {}

func (x *GetAllBannerAreasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBannerAreasRequest.ProtoReflect.Descriptor instead.
func (*GetAllBannerAreasRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{8}
}

type GetAllBannerAreasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerAreas   []*BannerArea          `protobuf:"bytes,1,rep,name=banner_areas,json=bannerAreas,proto3" json:"banner_areas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBannerAreasResponse) Reset() {
	*x = GetAllBannerAreasResponse{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBannerAreasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBannerAreasResponse) ProtoMessage() {}

func (x *GetAllBannerAreasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBannerAreasResponse.ProtoReflect.Descriptor instead.
func (*GetAllBannerAreasResponse) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllBannerAreasResponse) GetBannerAreas() []*BannerArea {
	if x != nil {
		return x.BannerAreas
	}
	return nil
}

type GetBannerAreaByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBannerAreaByIDRequest) Reset() {
	*x = GetBannerAreaByIDRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBannerAreaByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannerAreaByIDRequest) ProtoMessage() {}

func (x *GetBannerAreaByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannerAreaByIDRequest.ProtoReflect.Descriptor instead.
func (*GetBannerAreaByIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetBannerAreaByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateBannerAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	IsActive      *int32                 `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	IsAutoslide   *int32                 `protobuf:"varint,4,opt,name=is_autoslide,json=isAutoslide,proto3,oneof" json:"is_autoslide,omitempty"`
	PositionId    *int32                 `protobuf:"varint,5,opt,name=position_id,json=positionId,proto3,oneof" json:"position_id,omitempty"`
	SlideSpeed    *int32                 `protobuf:"varint,6,opt,name=slide_speed,json=slideSpeed,proto3,oneof" json:"slide_speed,omitempty"`
	SiteId        int32                  `protobuf:"varint,7,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBannerAreaRequest) Reset() {
	*x = CreateBannerAreaRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBannerAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBannerAreaRequest) ProtoMessage() {}

func (x *CreateBannerAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBannerAreaRequest.ProtoReflect.Descriptor instead.
func (*CreateBannerAreaRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBannerAreaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBannerAreaRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateBannerAreaRequest) GetIsActive() int32 {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return 0
}

func (x *CreateBannerAreaRequest) GetIsAutoslide() int32 {
	if x != nil && x.IsAutoslide != nil {
		return *x.IsAutoslide
	}
	return 0
}

func (x *CreateBannerAreaRequest) GetPositionId() int32 {
	if x != nil && x.PositionId != nil {
		return *x.PositionId
	}
	return 0
}

func (x *CreateBannerAreaRequest) GetSlideSpeed() int32 {
	if x != nil && x.SlideSpeed != nil {
		return *x.SlideSpeed
	}
	return 0
}

func (x *CreateBannerAreaRequest) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type UpdateBannerAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	IsActive      *int32                 `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	IsAutoslide   *int32                 `protobuf:"varint,5,opt,name=is_autoslide,json=isAutoslide,proto3,oneof" json:"is_autoslide,omitempty"`
	PositionId    *int32                 `protobuf:"varint,6,opt,name=position_id,json=positionId,proto3,oneof" json:"position_id,omitempty"`
	SlideSpeed    *int32                 `protobuf:"varint,7,opt,name=slide_speed,json=slideSpeed,proto3,oneof" json:"slide_speed,omitempty"`
	SiteId        int32                  `protobuf:"varint,8,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBannerAreaRequest) Reset() {
	*x = UpdateBannerAreaRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBannerAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBannerAreaRequest) ProtoMessage() {}

func (x *UpdateBannerAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBannerAreaRequest.ProtoReflect.Descriptor instead.
func (*UpdateBannerAreaRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateBannerAreaRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBannerAreaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBannerAreaRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateBannerAreaRequest) GetIsActive() int32 {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return 0
}

func (x *UpdateBannerAreaRequest) GetIsAutoslide() int32 {
	if x != nil && x.IsAutoslide != nil {
		return *x.IsAutoslide
	}
	return 0
}

func (x *UpdateBannerAreaRequest) GetPositionId() int32 {
	if x != nil && x.PositionId != nil {
		return *x.PositionId
	}
	return 0
}

func (x *UpdateBannerAreaRequest) GetSlideSpeed() int32 {
	if x != nil && x.SlideSpeed != nil {
		return *x.SlideSpeed
	}
	return 0
}

func (x *UpdateBannerAreaRequest) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type DeleteBannerAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBannerAreaRequest) Reset() {
	*x = DeleteBannerAreaRequest{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBannerAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerAreaRequest) ProtoMessage() {}

func (x *DeleteBannerAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerAreaRequest.ProtoReflect.Descriptor instead.
func (*DeleteBannerAreaRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteBannerAreaRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_v1_smart_cms_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_cms_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_v1_smart_cms_service_proto_rawDescGZIP(), []int{14}
}

var File_v1_smart_cms_service_proto protoreflect.FileDescriptor

const file_v1_smart_cms_service_proto_rawDesc = "" +
	"\n" +
	"\x1av1/smart-cms/service.proto\x12\vsmartcms.v1\"\xb9\t\n" +
	"\x06Banner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\x05R\x06siteId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12$\n" +
	"\vbanner_data\x18\x05 \x01(\tH\x01R\n" +
	"bannerData\x88\x01\x01\x12\x19\n" +
	"\x05order\x18\x06 \x01(\x05H\x02R\x05order\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\a \x01(\x05R\x04type\x12\"\n" +
	"\n" +
	"start_date\x18\b \x01(\tH\x03R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\t \x01(\tH\x04R\aendDate\x88\x01\x01\x12$\n" +
	"\vbutton_text\x18\n" +
	" \x01(\tH\x05R\n" +
	"buttonText\x88\x01\x01\x12$\n" +
	"\vbutton_link\x18\v \x01(\tH\x06R\n" +
	"buttonLink\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\f \x01(\x05R\bisActive\x12\x19\n" +
	"\x05image\x18\r \x01(\tH\aR\x05image\x88\x01\x01\x12&\n" +
	"\fmobile_title\x18\x0e \x01(\tH\bR\vmobileTitle\x88\x01\x01\x12\"\n" +
	"\n" +
	"mobile_url\x18\x0f \x01(\tH\tR\tmobileUrl\x88\x01\x01\x121\n" +
	"\x12mobile_banner_data\x18\x10 \x01(\tH\n" +
	"R\x10mobileBannerData\x88\x01\x01\x12&\n" +
	"\fmobile_order\x18\x11 \x01(\x05H\vR\vmobileOrder\x88\x01\x01\x12\x1f\n" +
	"\vmobile_type\x18\x12 \x01(\x05R\n" +
	"mobileType\x12/\n" +
	"\x11mobile_start_date\x18\x13 \x01(\tH\fR\x0fmobileStartDate\x88\x01\x01\x12+\n" +
	"\x0fmobile_end_date\x18\x14 \x01(\tH\rR\rmobileEndDate\x88\x01\x01\x12(\n" +
	"\x10mobile_is_active\x18\x15 \x01(\x05R\x0emobileIsActive\x121\n" +
	"\x12mobile_button_text\x18\x16 \x01(\tH\x0eR\x10mobileButtonText\x88\x01\x01\x121\n" +
	"\x12mobile_button_link\x18\x17 \x01(\tH\x0fR\x10mobileButtonLink\x88\x01\x01\x12&\n" +
	"\fmobile_image\x18\x18 \x01(\tH\x10R\vmobileImage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x19 \x01(\x05R\tsegmentId\x12$\n" +
	"\x0esite_show_type\x18\x1a \x01(\tR\fsiteShowTypeB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_banner_dataB\b\n" +
	"\x06_orderB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\x0e\n" +
	"\f_button_textB\x0e\n" +
	"\f_button_linkB\b\n" +
	"\x06_imageB\x0f\n" +
	"\r_mobile_titleB\r\n" +
	"\v_mobile_urlB\x15\n" +
	"\x13_mobile_banner_dataB\x0f\n" +
	"\r_mobile_orderB\x14\n" +
	"\x12_mobile_start_dateB\x12\n" +
	"\x10_mobile_end_dateB\x15\n" +
	"\x13_mobile_button_textB\x15\n" +
	"\x13_mobile_button_linkB\x0f\n" +
	"\r_mobile_image\"\xb2\x02\n" +
	"\n" +
	"BannerArea\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12 \n" +
	"\tis_active\x18\x04 \x01(\x05H\x00R\bisActive\x88\x01\x01\x12&\n" +
	"\fis_autoslide\x18\x05 \x01(\x05H\x01R\visAutoslide\x88\x01\x01\x12$\n" +
	"\vposition_id\x18\x06 \x01(\x05H\x02R\n" +
	"positionId\x88\x01\x01\x12$\n" +
	"\vslide_speed\x18\a \x01(\x05H\x03R\n" +
	"slideSpeed\x88\x01\x01\x12\x17\n" +
	"\asite_id\x18\b \x01(\x05R\x06siteIdB\f\n" +
	"\n" +
	"_is_activeB\x0f\n" +
	"\r_is_autoslideB\x0e\n" +
	"\f_position_idB\x0e\n" +
	"\f_slide_speed\"\x16\n" +
	"\x14GetAllBannersRequest\"F\n" +
	"\x15GetAllBannersResponse\x12-\n" +
	"\abanners\x18\x01 \x03(\v2\x13.smartcms.v1.BannerR\abanners\"&\n" +
	"\x14GetBannerByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xb6\t\n" +
	"\x13CreateBannerRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12$\n" +
	"\vbanner_data\x18\x04 \x01(\tH\x01R\n" +
	"bannerData\x88\x01\x01\x12\x19\n" +
	"\x05order\x18\x05 \x01(\x05H\x02R\x05order\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x05R\x04type\x12\"\n" +
	"\n" +
	"start_date\x18\a \x01(\tH\x03R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\b \x01(\tH\x04R\aendDate\x88\x01\x01\x12$\n" +
	"\vbutton_text\x18\t \x01(\tH\x05R\n" +
	"buttonText\x88\x01\x01\x12$\n" +
	"\vbutton_link\x18\n" +
	" \x01(\tH\x06R\n" +
	"buttonLink\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\v \x01(\x05R\bisActive\x12\x19\n" +
	"\x05image\x18\f \x01(\tH\aR\x05image\x88\x01\x01\x12&\n" +
	"\fmobile_title\x18\r \x01(\tH\bR\vmobileTitle\x88\x01\x01\x12\"\n" +
	"\n" +
	"mobile_url\x18\x0e \x01(\tH\tR\tmobileUrl\x88\x01\x01\x121\n" +
	"\x12mobile_banner_data\x18\x0f \x01(\tH\n" +
	"R\x10mobileBannerData\x88\x01\x01\x12&\n" +
	"\fmobile_order\x18\x10 \x01(\x05H\vR\vmobileOrder\x88\x01\x01\x12\x1f\n" +
	"\vmobile_type\x18\x11 \x01(\x05R\n" +
	"mobileType\x12/\n" +
	"\x11mobile_start_date\x18\x12 \x01(\tH\fR\x0fmobileStartDate\x88\x01\x01\x12+\n" +
	"\x0fmobile_end_date\x18\x13 \x01(\tH\rR\rmobileEndDate\x88\x01\x01\x12(\n" +
	"\x10mobile_is_active\x18\x14 \x01(\x05R\x0emobileIsActive\x121\n" +
	"\x12mobile_button_text\x18\x15 \x01(\tH\x0eR\x10mobileButtonText\x88\x01\x01\x121\n" +
	"\x12mobile_button_link\x18\x16 \x01(\tH\x0fR\x10mobileButtonLink\x88\x01\x01\x12&\n" +
	"\fmobile_image\x18\x17 \x01(\tH\x10R\vmobileImage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x18 \x01(\x05R\tsegmentId\x12$\n" +
	"\x0esite_show_type\x18\x19 \x01(\tR\fsiteShowTypeB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_banner_dataB\b\n" +
	"\x06_orderB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\x0e\n" +
	"\f_button_textB\x0e\n" +
	"\f_button_linkB\b\n" +
	"\x06_imageB\x0f\n" +
	"\r_mobile_titleB\r\n" +
	"\v_mobile_urlB\x15\n" +
	"\x13_mobile_banner_dataB\x0f\n" +
	"\r_mobile_orderB\x14\n" +
	"\x12_mobile_start_dateB\x12\n" +
	"\x10_mobile_end_dateB\x15\n" +
	"\x13_mobile_button_textB\x15\n" +
	"\x13_mobile_button_linkB\x0f\n" +
	"\r_mobile_image\"\xc6\t\n" +
	"\x13UpdateBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\x05R\x06siteId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12$\n" +
	"\vbanner_data\x18\x05 \x01(\tH\x01R\n" +
	"bannerData\x88\x01\x01\x12\x19\n" +
	"\x05order\x18\x06 \x01(\x05H\x02R\x05order\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\a \x01(\x05R\x04type\x12\"\n" +
	"\n" +
	"start_date\x18\b \x01(\tH\x03R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\t \x01(\tH\x04R\aendDate\x88\x01\x01\x12$\n" +
	"\vbutton_text\x18\n" +
	" \x01(\tH\x05R\n" +
	"buttonText\x88\x01\x01\x12$\n" +
	"\vbutton_link\x18\v \x01(\tH\x06R\n" +
	"buttonLink\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\f \x01(\x05R\bisActive\x12\x19\n" +
	"\x05image\x18\r \x01(\tH\aR\x05image\x88\x01\x01\x12&\n" +
	"\fmobile_title\x18\x0e \x01(\tH\bR\vmobileTitle\x88\x01\x01\x12\"\n" +
	"\n" +
	"mobile_url\x18\x0f \x01(\tH\tR\tmobileUrl\x88\x01\x01\x121\n" +
	"\x12mobile_banner_data\x18\x10 \x01(\tH\n" +
	"R\x10mobileBannerData\x88\x01\x01\x12&\n" +
	"\fmobile_order\x18\x11 \x01(\x05H\vR\vmobileOrder\x88\x01\x01\x12\x1f\n" +
	"\vmobile_type\x18\x12 \x01(\x05R\n" +
	"mobileType\x12/\n" +
	"\x11mobile_start_date\x18\x13 \x01(\tH\fR\x0fmobileStartDate\x88\x01\x01\x12+\n" +
	"\x0fmobile_end_date\x18\x14 \x01(\tH\rR\rmobileEndDate\x88\x01\x01\x12(\n" +
	"\x10mobile_is_active\x18\x15 \x01(\x05R\x0emobileIsActive\x121\n" +
	"\x12mobile_button_text\x18\x16 \x01(\tH\x0eR\x10mobileButtonText\x88\x01\x01\x121\n" +
	"\x12mobile_button_link\x18\x17 \x01(\tH\x0fR\x10mobileButtonLink\x88\x01\x01\x12&\n" +
	"\fmobile_image\x18\x18 \x01(\tH\x10R\vmobileImage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x19 \x01(\x05R\tsegmentId\x12$\n" +
	"\x0esite_show_type\x18\x1a \x01(\tR\fsiteShowTypeB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_banner_dataB\b\n" +
	"\x06_orderB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\x0e\n" +
	"\f_button_textB\x0e\n" +
	"\f_button_linkB\b\n" +
	"\x06_imageB\x0f\n" +
	"\r_mobile_titleB\r\n" +
	"\v_mobile_urlB\x15\n" +
	"\x13_mobile_banner_dataB\x0f\n" +
	"\r_mobile_orderB\x14\n" +
	"\x12_mobile_start_dateB\x12\n" +
	"\x10_mobile_end_dateB\x15\n" +
	"\x13_mobile_button_textB\x15\n" +
	"\x13_mobile_button_linkB\x0f\n" +
	"\r_mobile_image\"%\n" +
	"\x13DeleteBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x1a\n" +
	"\x18GetAllBannerAreasRequest\"W\n" +
	"\x19GetAllBannerAreasResponse\x12:\n" +
	"\fbanner_areas\x18\x01 \x03(\v2\x17.smartcms.v1.BannerAreaR\vbannerAreas\"*\n" +
	"\x18GetBannerAreaByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xaf\x02\n" +
	"\x17CreateBannerAreaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12 \n" +
	"\tis_active\x18\x03 \x01(\x05H\x00R\bisActive\x88\x01\x01\x12&\n" +
	"\fis_autoslide\x18\x04 \x01(\x05H\x01R\visAutoslide\x88\x01\x01\x12$\n" +
	"\vposition_id\x18\x05 \x01(\x05H\x02R\n" +
	"positionId\x88\x01\x01\x12$\n" +
	"\vslide_speed\x18\x06 \x01(\x05H\x03R\n" +
	"slideSpeed\x88\x01\x01\x12\x17\n" +
	"\asite_id\x18\a \x01(\x05R\x06siteIdB\f\n" +
	"\n" +
	"_is_activeB\x0f\n" +
	"\r_is_autoslideB\x0e\n" +
	"\f_position_idB\x0e\n" +
	"\f_slide_speed\"\xbf\x02\n" +
	"\x17UpdateBannerAreaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12 \n" +
	"\tis_active\x18\x04 \x01(\x05H\x00R\bisActive\x88\x01\x01\x12&\n" +
	"\fis_autoslide\x18\x05 \x01(\x05H\x01R\visAutoslide\x88\x01\x01\x12$\n" +
	"\vposition_id\x18\x06 \x01(\x05H\x02R\n" +
	"positionId\x88\x01\x01\x12$\n" +
	"\vslide_speed\x18\a \x01(\x05H\x03R\n" +
	"slideSpeed\x88\x01\x01\x12\x17\n" +
	"\asite_id\x18\b \x01(\x05R\x06siteIdB\f\n" +
	"\n" +
	"_is_activeB\x0f\n" +
	"\r_is_autoslideB\x0e\n" +
	"\f_position_idB\x0e\n" +
	"\f_slide_speed\")\n" +
	"\x17DeleteBannerAreaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\a\n" +
	"\x05Empty2\xb3\x06\n" +
	"\x0fSmartCMSService\x12V\n" +
	"\rGetAllBanners\x12!.smartcms.v1.GetAllBannersRequest\x1a\".smartcms.v1.GetAllBannersResponse\x12G\n" +
	"\rGetBannerByID\x12!.smartcms.v1.GetBannerByIDRequest\x1a\x13.smartcms.v1.Banner\x12E\n" +
	"\fCreateBanner\x12 .smartcms.v1.CreateBannerRequest\x1a\x13.smartcms.v1.Banner\x12E\n" +
	"\fUpdateBanner\x12 .smartcms.v1.UpdateBannerRequest\x1a\x13.smartcms.v1.Banner\x12D\n" +
	"\fDeleteBanner\x12 .smartcms.v1.DeleteBannerRequest\x1a\x12.smartcms.v1.Empty\x12b\n" +
	"\x11GetAllBannerAreas\x12%.smartcms.v1.GetAllBannerAreasRequest\x1a&.smartcms.v1.GetAllBannerAreasResponse\x12S\n" +
	"\x11GetBannerAreaByID\x12%.smartcms.v1.GetBannerAreaByIDRequest\x1a\x17.smartcms.v1.BannerArea\x12Q\n" +
	"\x10CreateBannerArea\x12$.smartcms.v1.CreateBannerAreaRequest\x1a\x17.smartcms.v1.BannerArea\x12Q\n" +
	"\x10UpdateBannerArea\x12$.smartcms.v1.UpdateBannerAreaRequest\x1a\x17.smartcms.v1.BannerArea\x12L\n" +
	"\x10DeleteBannerArea\x12$.smartcms.v1.DeleteBannerAreaRequest\x1a\x12.smartcms.v1.EmptyB%Z#smartcms/pb/v1/smart-cms;smartcmsv1b\x06proto3"

var (
	file_v1_smart_cms_service_proto_rawDescOnce sync.Once
	file_v1_smart_cms_service_proto_rawDescData []byte
)

func file_v1_smart_cms_service_proto_rawDescGZIP() []byte {
	file_v1_smart_cms_service_proto_rawDescOnce.Do(func() {
		file_v1_smart_cms_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_smart_cms_service_proto_rawDesc), len(file_v1_smart_cms_service_proto_rawDesc)))
	})
	return file_v1_smart_cms_service_proto_rawDescData
}

var file_v1_smart_cms_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_smart_cms_service_proto_goTypes = []any{
	(*Banner)(nil),                    // 0: smartcms.v1.Banner
	(*BannerArea)(nil),                // 1: smartcms.v1.BannerArea
	(*GetAllBannersRequest)(nil),      // 2: smartcms.v1.GetAllBannersRequest
	(*GetAllBannersResponse)(nil),     // 3: smartcms.v1.GetAllBannersResponse
	(*GetBannerByIDRequest)(nil),      // 4: smartcms.v1.GetBannerByIDRequest
	(*CreateBannerRequest)(nil),       // 5: smartcms.v1.CreateBannerRequest
	(*UpdateBannerRequest)(nil),       // 6: smartcms.v1.UpdateBannerRequest
	(*DeleteBannerRequest)(nil),       // 7: smartcms.v1.DeleteBannerRequest
	(*GetAllBannerAreasRequest)(nil),  // 8: smartcms.v1.GetAllBannerAreasRequest
	(*GetAllBannerAreasResponse)(nil), // 9: smartcms.v1.GetAllBannerAreasResponse
	(*GetBannerAreaByIDRequest)(nil),  // 10: smartcms.v1.GetBannerAreaByIDRequest
	(*CreateBannerAreaRequest)(nil),   // 11: smartcms.v1.CreateBannerAreaRequest
	(*UpdateBannerAreaRequest)(nil),   // 12: smartcms.v1.UpdateBannerAreaRequest
	(*DeleteBannerAreaRequest)(nil),   // 13: smartcms.v1.DeleteBannerAreaRequest
	(*Empty)(nil),                     // 14: smartcms.v1.Empty
}
var file_v1_smart_cms_service_proto_depIdxs = []int32{
	0,  // 0: smartcms.v1.GetAllBannersResponse.banners:type_name -> smartcms.v1.Banner
	1,  // 1: smartcms.v1.GetAllBannerAreasResponse.banner_areas:type_name -> smartcms.v1.BannerArea
	2,  // 2: smartcms.v1.SmartCMSService.GetAllBanners:input_type -> smartcms.v1.GetAllBannersRequest
	4,  // 3: smartcms.v1.SmartCMSService.GetBannerByID:input_type -> smartcms.v1.GetBannerByIDRequest
	5,  // 4: smartcms.v1.SmartCMSService.CreateBanner:input_type -> smartcms.v1.CreateBannerRequest
	6,  // 5: smartcms.v1.SmartCMSService.UpdateBanner:input_type -> smartcms.v1.UpdateBannerRequest
	7,  // 6: smartcms.v1.SmartCMSService.DeleteBanner:input_type -> smartcms.v1.DeleteBannerRequest
	8,  // 7: smartcms.v1.SmartCMSService.GetAllBannerAreas:input_type -> smartcms.v1.GetAllBannerAreasRequest
	10, // 8: smartcms.v1.SmartCMSService.GetBannerAreaByID:input_type -> smartcms.v1.GetBannerAreaByIDRequest
	11, // 9: smartcms.v1.SmartCMSService.CreateBannerArea:input_type -> smartcms.v1.CreateBannerAreaRequest
	12, // 10: smartcms.v1.SmartCMSService.UpdateBannerArea:input_type -> smartcms.v1.UpdateBannerAreaRequest
	13, // 11: smartcms.v1.SmartCMSService.DeleteBannerArea:input_type -> smartcms.v1.DeleteBannerAreaRequest
	3,  // 12: smartcms.v1.SmartCMSService.GetAllBanners:output_type -> smartcms.v1.GetAllBannersResponse
	0,  // 13: smartcms.v1.SmartCMSService.GetBannerByID:output_type -> smartcms.v1.Banner
	0,  // 14: smartcms.v1.SmartCMSService.CreateBanner:output_type -> smartcms.v1.Banner
	0,  // 15: smartcms.v1.SmartCMSService.UpdateBanner:output_type -> smartcms.v1.Banner
	14, // 16: smartcms.v1.SmartCMSService.DeleteBanner:output_type -> smartcms.v1.Empty
	9,  // 17: smartcms.v1.SmartCMSService.GetAllBannerAreas:output_type -> smartcms.v1.GetAllBannerAreasResponse
	1,  // 18: smartcms.v1.SmartCMSService.GetBannerAreaByID:output_type -> smartcms.v1.BannerArea
	1,  // 19: smartcms.v1.SmartCMSService.CreateBannerArea:output_type -> smartcms.v1.BannerArea
	1,  // 20: smartcms.v1.SmartCMSService.UpdateBannerArea:output_type -> smartcms.v1.BannerArea
	14, // 21: smartcms.v1.SmartCMSService.DeleteBannerArea:output_type -> smartcms.v1.Empty
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_v1_smart_cms_service_proto_init() }
func file_v1_smart_cms_service_proto_init() {
	if File_v1_smart_cms_service_proto != nil {
		return
	}
	file_v1_smart_cms_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_smart_cms_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_smart_cms_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_v1_smart_cms_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_v1_smart_cms_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_v1_smart_cms_service_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_smart_cms_service_proto_rawDesc), len(file_v1_smart_cms_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_smart_cms_service_proto_goTypes,
		DependencyIndexes: file_v1_smart_cms_service_proto_depIdxs,
		MessageInfos:      file_v1_smart_cms_service_proto_msgTypes,
	}.Build()
	File_v1_smart_cms_service_proto = out.File
	file_v1_smart_cms_service_proto_goTypes = nil
	file_v1_smart_cms_service_proto_depIdxs = nil
}
