// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/smart-cms/service.proto

package smartcmsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmartCMSService_GetAllBanners_FullMethodName     = "/smartcms.v1.SmartCMSService/GetAllBanners"
	SmartCMSService_GetBannerByID_FullMethodName     = "/smartcms.v1.SmartCMSService/GetBannerByID"
	SmartCMSService_CreateBanner_FullMethodName      = "/smartcms.v1.SmartCMSService/CreateBanner"
	SmartCMSService_UpdateBanner_FullMethodName      = "/smartcms.v1.SmartCMSService/UpdateBanner"
	SmartCMSService_DeleteBanner_FullMethodName      = "/smartcms.v1.SmartCMSService/DeleteBanner"
	SmartCMSService_GetAllBannerAreas_FullMethodName = "/smartcms.v1.SmartCMSService/GetAllBannerAreas"
	SmartCMSService_GetBannerAreaByID_FullMethodName = "/smartcms.v1.SmartCMSService/GetBannerAreaByID"
	SmartCMSService_CreateBannerArea_FullMethodName  = "/smartcms.v1.SmartCMSService/CreateBannerArea"
	SmartCMSService_UpdateBannerArea_FullMethodName  = "/smartcms.v1.SmartCMSService/UpdateBannerArea"
	SmartCMSService_DeleteBannerArea_FullMethodName  = "/smartcms.v1.SmartCMSService/DeleteBannerArea"
)

// SmartCMSServiceClient is the client API for SmartCMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartCMSServiceClient interface {
	// Banner RPCs
	GetAllBanners(ctx context.Context, in *GetAllBannersRequest, opts ...grpc.CallOption) (*GetAllBannersResponse, error)
	GetBannerByID(ctx context.Context, in *GetBannerByIDRequest, opts ...grpc.CallOption) (*Banner, error)
	CreateBanner(ctx context.Context, in *CreateBannerRequest, opts ...grpc.CallOption) (*Banner, error)
	UpdateBanner(ctx context.Context, in *UpdateBannerRequest, opts ...grpc.CallOption) (*Banner, error)
	DeleteBanner(ctx context.Context, in *DeleteBannerRequest, opts ...grpc.CallOption) (*Empty, error)
	// BannerArea RPCs
	GetAllBannerAreas(ctx context.Context, in *GetAllBannerAreasRequest, opts ...grpc.CallOption) (*GetAllBannerAreasResponse, error)
	GetBannerAreaByID(ctx context.Context, in *GetBannerAreaByIDRequest, opts ...grpc.CallOption) (*BannerArea, error)
	CreateBannerArea(ctx context.Context, in *CreateBannerAreaRequest, opts ...grpc.CallOption) (*BannerArea, error)
	UpdateBannerArea(ctx context.Context, in *UpdateBannerAreaRequest, opts ...grpc.CallOption) (*BannerArea, error)
	DeleteBannerArea(ctx context.Context, in *DeleteBannerAreaRequest, opts ...grpc.CallOption) (*Empty, error)
}

type smartCMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartCMSServiceClient(cc grpc.ClientConnInterface) SmartCMSServiceClient {
	return &smartCMSServiceClient{cc}
}

func (c *smartCMSServiceClient) GetAllBanners(ctx context.Context, in *GetAllBannersRequest, opts ...grpc.CallOption) (*GetAllBannersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllBannersResponse)
	err := c.cc.Invoke(ctx, SmartCMSService_GetAllBanners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCMSServiceClient) GetBannerByID(ctx context.Context, in *GetBannerByIDRequest, opts ...grpc.CallOption) (*Banner, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Banner)
	err := c.cc.Invoke(ctx, SmartCMSService_GetBannerByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCMSServiceClient) CreateBanner(ctx context.Context, in *CreateBannerRequest, opts ...grpc.CallOption) (*Banner, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Banner)
	err := c.cc.Invoke(ctx, SmartCMSService_CreateBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCMSServiceClient) UpdateBanner(ctx context.Context, in *UpdateBannerRequest, opts ...grpc.CallOption) (*Banner, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Banner)
	err := c.cc.Invoke(ctx, SmartCMSService_UpdateBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCMSServiceClient) DeleteBanner(ctx context.Context, in *DeleteBannerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SmartCMSService_DeleteBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCMSServiceClient) GetAllBannerAreas(ctx context.Context, in *GetAllBannerAreasRequest, opts ...grpc.CallOption) (*GetAllBannerAreasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllBannerAreasResponse)
	err := c.cc.Invoke(ctx, SmartCMSService_GetAllBannerAreas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCMSServiceClient) GetBannerAreaByID(ctx context.Context, in *GetBannerAreaByIDRequest, opts ...grpc.CallOption) (*BannerArea, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BannerArea)
	err := c.cc.Invoke(ctx, SmartCMSService_GetBannerAreaByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCMSServiceClient) CreateBannerArea(ctx context.Context, in *CreateBannerAreaRequest, opts ...grpc.CallOption) (*BannerArea, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BannerArea)
	err := c.cc.Invoke(ctx, SmartCMSService_CreateBannerArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCMSServiceClient) UpdateBannerArea(ctx context.Context, in *UpdateBannerAreaRequest, opts ...grpc.CallOption) (*BannerArea, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BannerArea)
	err := c.cc.Invoke(ctx, SmartCMSService_UpdateBannerArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCMSServiceClient) DeleteBannerArea(ctx context.Context, in *DeleteBannerAreaRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SmartCMSService_DeleteBannerArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartCMSServiceServer is the server API for SmartCMSService service.
// All implementations must embed UnimplementedSmartCMSServiceServer
// for forward compatibility.
type SmartCMSServiceServer interface {
	// Banner RPCs
	GetAllBanners(context.Context, *GetAllBannersRequest) (*GetAllBannersResponse, error)
	GetBannerByID(context.Context, *GetBannerByIDRequest) (*Banner, error)
	CreateBanner(context.Context, *CreateBannerRequest) (*Banner, error)
	UpdateBanner(context.Context, *UpdateBannerRequest) (*Banner, error)
	DeleteBanner(context.Context, *DeleteBannerRequest) (*Empty, error)
	// BannerArea RPCs
	GetAllBannerAreas(context.Context, *GetAllBannerAreasRequest) (*GetAllBannerAreasResponse, error)
	GetBannerAreaByID(context.Context, *GetBannerAreaByIDRequest) (*BannerArea, error)
	CreateBannerArea(context.Context, *CreateBannerAreaRequest) (*BannerArea, error)
	UpdateBannerArea(context.Context, *UpdateBannerAreaRequest) (*BannerArea, error)
	DeleteBannerArea(context.Context, *DeleteBannerAreaRequest) (*Empty, error)
	mustEmbedUnimplementedSmartCMSServiceServer()
}

// UnimplementedSmartCMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmartCMSServiceServer struct{}

func (UnimplementedSmartCMSServiceServer) GetAllBanners(context.Context, *GetAllBannersRequest) (*GetAllBannersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllBanners not implemented")
}
func (UnimplementedSmartCMSServiceServer) GetBannerByID(context.Context, *GetBannerByIDRequest) (*Banner, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBannerByID not implemented")
}
func (UnimplementedSmartCMSServiceServer) CreateBanner(context.Context, *CreateBannerRequest) (*Banner, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBanner not implemented")
}
func (UnimplementedSmartCMSServiceServer) UpdateBanner(context.Context, *UpdateBannerRequest) (*Banner, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBanner not implemented")
}
func (UnimplementedSmartCMSServiceServer) DeleteBanner(context.Context, *DeleteBannerRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBanner not implemented")
}
func (UnimplementedSmartCMSServiceServer) GetAllBannerAreas(context.Context, *GetAllBannerAreasRequest) (*GetAllBannerAreasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllBannerAreas not implemented")
}
func (UnimplementedSmartCMSServiceServer) GetBannerAreaByID(context.Context, *GetBannerAreaByIDRequest) (*BannerArea, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBannerAreaByID not implemented")
}
func (UnimplementedSmartCMSServiceServer) CreateBannerArea(context.Context, *CreateBannerAreaRequest) (*BannerArea, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBannerArea not implemented")
}
func (UnimplementedSmartCMSServiceServer) UpdateBannerArea(context.Context, *UpdateBannerAreaRequest) (*BannerArea, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBannerArea not implemented")
}
func (UnimplementedSmartCMSServiceServer) DeleteBannerArea(context.Context, *DeleteBannerAreaRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBannerArea not implemented")
}
func (UnimplementedSmartCMSServiceServer) mustEmbedUnimplementedSmartCMSServiceServer() {}
func (UnimplementedSmartCMSServiceServer) testEmbeddedByValue()                         {}

// UnsafeSmartCMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartCMSServiceServer will
// result in compilation errors.
type UnsafeSmartCMSServiceServer interface {
	mustEmbedUnimplementedSmartCMSServiceServer()
}

func RegisterSmartCMSServiceServer(s grpc.ServiceRegistrar, srv SmartCMSServiceServer) {
	// If the following call panics, it indicates UnimplementedSmartCMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmartCMSService_ServiceDesc, srv)
}

func _SmartCMSService_GetAllBanners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBannersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).GetAllBanners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_GetAllBanners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).GetAllBanners(ctx, req.(*GetAllBannersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCMSService_GetBannerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).GetBannerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_GetBannerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).GetBannerByID(ctx, req.(*GetBannerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCMSService_CreateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).CreateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_CreateBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).CreateBanner(ctx, req.(*CreateBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCMSService_UpdateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).UpdateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_UpdateBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).UpdateBanner(ctx, req.(*UpdateBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCMSService_DeleteBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).DeleteBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_DeleteBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).DeleteBanner(ctx, req.(*DeleteBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCMSService_GetAllBannerAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBannerAreasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).GetAllBannerAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_GetAllBannerAreas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).GetAllBannerAreas(ctx, req.(*GetAllBannerAreasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCMSService_GetBannerAreaByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannerAreaByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).GetBannerAreaByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_GetBannerAreaByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).GetBannerAreaByID(ctx, req.(*GetBannerAreaByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCMSService_CreateBannerArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBannerAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).CreateBannerArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_CreateBannerArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).CreateBannerArea(ctx, req.(*CreateBannerAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCMSService_UpdateBannerArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBannerAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).UpdateBannerArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_UpdateBannerArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).UpdateBannerArea(ctx, req.(*UpdateBannerAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCMSService_DeleteBannerArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBannerAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCMSServiceServer).DeleteBannerArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCMSService_DeleteBannerArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCMSServiceServer).DeleteBannerArea(ctx, req.(*DeleteBannerAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartCMSService_ServiceDesc is the grpc.ServiceDesc for SmartCMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartCMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartcms.v1.SmartCMSService",
	HandlerType: (*SmartCMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllBanners",
			Handler:    _SmartCMSService_GetAllBanners_Handler,
		},
		{
			MethodName: "GetBannerByID",
			Handler:    _SmartCMSService_GetBannerByID_Handler,
		},
		{
			MethodName: "CreateBanner",
			Handler:    _SmartCMSService_CreateBanner_Handler,
		},
		{
			MethodName: "UpdateBanner",
			Handler:    _SmartCMSService_UpdateBanner_Handler,
		},
		{
			MethodName: "DeleteBanner",
			Handler:    _SmartCMSService_DeleteBanner_Handler,
		},
		{
			MethodName: "GetAllBannerAreas",
			Handler:    _SmartCMSService_GetAllBannerAreas_Handler,
		},
		{
			MethodName: "GetBannerAreaByID",
			Handler:    _SmartCMSService_GetBannerAreaByID_Handler,
		},
		{
			MethodName: "CreateBannerArea",
			Handler:    _SmartCMSService_CreateBannerArea_Handler,
		},
		{
			MethodName: "UpdateBannerArea",
			Handler:    _SmartCMSService_UpdateBannerArea_Handler,
		},
		{
			MethodName: "DeleteBannerArea",
			Handler:    _SmartCMSService_DeleteBannerArea_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/smart-cms/service.proto",
}
