// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/smart-image/service.proto

package smartimagev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Size          *Size                  `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_v1_smart_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_v1_smart_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UploadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *UploadRequest) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_v1_smart_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_v1_smart_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *Size) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Size) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_v1_smart_image_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_v1_smart_image_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_v1_smart_image_service_proto_rawDescGZIP(), []int{2}
}

var File_v1_smart_image_service_proto protoreflect.FileDescriptor

const file_v1_smart_image_service_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/smart-image/service.proto\x12\rsmartimage.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x8a\x01\n" +
	"\rUploadRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12'\n" +
	"\x04size\x18\x05 \x01(\v2\x13.smartimage.v1.SizeR\x04size\"4\n" +
	"\x04Size\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"\a\n" +
	"\x05Empty2X\n" +
	"\x11SmartImageService\x12C\n" +
	"\vUploadImage\x12\x1c.smartimage.v1.UploadRequest\x1a\x14.smartimage.v1.Empty\"\x00BFZDgitlab.smartbet.am/common/api-schema/gen/smart-image/v1;smartimagev1b\x06proto3"

var (
	file_v1_smart_image_service_proto_rawDescOnce sync.Once
	file_v1_smart_image_service_proto_rawDescData []byte
)

func file_v1_smart_image_service_proto_rawDescGZIP() []byte {
	file_v1_smart_image_service_proto_rawDescOnce.Do(func() {
		file_v1_smart_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_smart_image_service_proto_rawDesc), len(file_v1_smart_image_service_proto_rawDesc)))
	})
	return file_v1_smart_image_service_proto_rawDescData
}

var file_v1_smart_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_smart_image_service_proto_goTypes = []any{
	(*UploadRequest)(nil), // 0: smartimage.v1.UploadRequest
	(*Size)(nil),          // 1: smartimage.v1.Size
	(*Empty)(nil),         // 2: smartimage.v1.Empty
}
var file_v1_smart_image_service_proto_depIdxs = []int32{
	1, // 0: smartimage.v1.UploadRequest.size:type_name -> smartimage.v1.Size
	0, // 1: smartimage.v1.SmartImageService.UploadImage:input_type -> smartimage.v1.UploadRequest
	2, // 2: smartimage.v1.SmartImageService.UploadImage:output_type -> smartimage.v1.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_smart_image_service_proto_init() }
func file_v1_smart_image_service_proto_init() {
	if File_v1_smart_image_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_smart_image_service_proto_rawDesc), len(file_v1_smart_image_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_smart_image_service_proto_goTypes,
		DependencyIndexes: file_v1_smart_image_service_proto_depIdxs,
		MessageInfos:      file_v1_smart_image_service_proto_msgTypes,
	}.Build()
	File_v1_smart_image_service_proto = out.File
	file_v1_smart_image_service_proto_goTypes = nil
	file_v1_smart_image_service_proto_depIdxs = nil
}
