// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/smart-image/service.proto

package smartimagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmartImageService_UploadImage_FullMethodName = "/smartimage.v1.SmartImageService/UploadImage"
)

// SmartImageServiceClient is the client API for SmartImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartImageServiceClient interface {
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	UploadImage(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*Empty, error)
}

type smartImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartImageServiceClient(cc grpc.ClientConnInterface) SmartImageServiceClient {
	return &smartImageServiceClient{cc}
}

func (c *smartImageServiceClient) UploadImage(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SmartImageService_UploadImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartImageServiceServer is the server API for SmartImageService service.
// All implementations must embed UnimplementedSmartImageServiceServer
// for forward compatibility.
type SmartImageServiceServer interface {
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	UploadImage(context.Context, *UploadRequest) (*Empty, error)
	mustEmbedUnimplementedSmartImageServiceServer()
}

// UnimplementedSmartImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmartImageServiceServer struct{}

func (UnimplementedSmartImageServiceServer) UploadImage(context.Context, *UploadRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedSmartImageServiceServer) mustEmbedUnimplementedSmartImageServiceServer() {}
func (UnimplementedSmartImageServiceServer) testEmbeddedByValue()                           {}

// UnsafeSmartImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartImageServiceServer will
// result in compilation errors.
type UnsafeSmartImageServiceServer interface {
	mustEmbedUnimplementedSmartImageServiceServer()
}

func RegisterSmartImageServiceServer(s grpc.ServiceRegistrar, srv SmartImageServiceServer) {
	// If the following call panics, it indicates UnimplementedSmartImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmartImageService_ServiceDesc, srv)
}

func _SmartImageService_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartImageServiceServer).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartImageService_UploadImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartImageServiceServer).UploadImage(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartImageService_ServiceDesc is the grpc.ServiceDesc for SmartImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartimage.v1.SmartImageService",
	HandlerType: (*SmartImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadImage",
			Handler:    _SmartImageService_UploadImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/smart-image/service.proto",
}
