// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Phoenix365-tech/imagix/ent/image"
	"github.com/Phoenix365-tech/imagix/ent/predicate"
	"github.com/Phoenix365-tech/imagix/internal/service/processor"
)

// ImageUpdate is the builder for updating Image entities.
type ImageUpdate struct {
	config
	hooks    []Hook
	mutation *ImageMutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (iu *ImageUpdate) Where(ps ...predicate.Image) *ImageUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetUpdateTime sets the "update_time" field.
func (iu *ImageUpdate) SetUpdateTime(t time.Time) *ImageUpdate {
	iu.mutation.SetUpdateTime(t)
	return iu
}

// SetUUID sets the "uuid" field.
func (iu *ImageUpdate) SetUUID(s string) *ImageUpdate {
	iu.mutation.SetUUID(s)
	return iu
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableUUID(s *string) *ImageUpdate {
	if s != nil {
		iu.SetUUID(*s)
	}
	return iu
}

// SetURL sets the "url" field.
func (iu *ImageUpdate) SetURL(s string) *ImageUpdate {
	iu.mutation.SetURL(s)
	return iu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableURL(s *string) *ImageUpdate {
	if s != nil {
		iu.SetURL(*s)
	}
	return iu
}

// ClearURL clears the value of the "url" field.
func (iu *ImageUpdate) ClearURL() *ImageUpdate {
	iu.mutation.ClearURL()
	return iu
}

// SetObjectID sets the "object_id" field.
func (iu *ImageUpdate) SetObjectID(s string) *ImageUpdate {
	iu.mutation.SetObjectID(s)
	return iu
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableObjectID(s *string) *ImageUpdate {
	if s != nil {
		iu.SetObjectID(*s)
	}
	return iu
}

// ClearObjectID clears the value of the "object_id" field.
func (iu *ImageUpdate) ClearObjectID() *ImageUpdate {
	iu.mutation.ClearObjectID()
	return iu
}

// SetTmpURL sets the "tmp_url" field.
func (iu *ImageUpdate) SetTmpURL(s string) *ImageUpdate {
	iu.mutation.SetTmpURL(s)
	return iu
}

// SetNillableTmpURL sets the "tmp_url" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableTmpURL(s *string) *ImageUpdate {
	if s != nil {
		iu.SetTmpURL(*s)
	}
	return iu
}

// SetService sets the "service" field.
func (iu *ImageUpdate) SetService(s string) *ImageUpdate {
	iu.mutation.SetService(s)
	return iu
}

// SetNillableService sets the "service" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableService(s *string) *ImageUpdate {
	if s != nil {
		iu.SetService(*s)
	}
	return iu
}

// ClearService clears the value of the "service" field.
func (iu *ImageUpdate) ClearService() *ImageUpdate {
	iu.mutation.ClearService()
	return iu
}

// SetType sets the "type" field.
func (iu *ImageUpdate) SetType(s string) *ImageUpdate {
	iu.mutation.SetType(s)
	return iu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableType(s *string) *ImageUpdate {
	if s != nil {
		iu.SetType(*s)
	}
	return iu
}

// ClearType clears the value of the "type" field.
func (iu *ImageUpdate) ClearType() *ImageUpdate {
	iu.mutation.ClearType()
	return iu
}

// SetIsProceed sets the "is_proceed" field.
func (iu *ImageUpdate) SetIsProceed(b bool) *ImageUpdate {
	iu.mutation.SetIsProceed(b)
	return iu
}

// SetNillableIsProceed sets the "is_proceed" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableIsProceed(b *bool) *ImageUpdate {
	if b != nil {
		iu.SetIsProceed(*b)
	}
	return iu
}

// SetIsDeleted sets the "is_deleted" field.
func (iu *ImageUpdate) SetIsDeleted(b bool) *ImageUpdate {
	iu.mutation.SetIsDeleted(b)
	return iu
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableIsDeleted(b *bool) *ImageUpdate {
	if b != nil {
		iu.SetIsDeleted(*b)
	}
	return iu
}

// SetContentType sets the "content_type" field.
func (iu *ImageUpdate) SetContentType(s string) *ImageUpdate {
	iu.mutation.SetContentType(s)
	return iu
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableContentType(s *string) *ImageUpdate {
	if s != nil {
		iu.SetContentType(*s)
	}
	return iu
}

// SetSize sets the "size" field.
func (iu *ImageUpdate) SetSize(pr processor.Size) *ImageUpdate {
	iu.mutation.SetSize(pr)
	return iu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableSize(pr *processor.Size) *ImageUpdate {
	if pr != nil {
		iu.SetSize(*pr)
	}
	return iu
}

// ClearSize clears the value of the "size" field.
func (iu *ImageUpdate) ClearSize() *ImageUpdate {
	iu.mutation.ClearSize()
	return iu
}

// Mutation returns the ImageMutation object of the builder.
func (iu *ImageUpdate) Mutation() *ImageMutation {
	return iu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *ImageUpdate) Save(ctx context.Context) (int, error) {
	iu.defaults()
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *ImageUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *ImageUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *ImageUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iu *ImageUpdate) defaults() {
	if _, ok := iu.mutation.UpdateTime(); !ok {
		v := image.UpdateDefaultUpdateTime()
		iu.mutation.SetUpdateTime(v)
	}
}

func (iu *ImageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.UpdateTime(); ok {
		_spec.SetField(image.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := iu.mutation.UUID(); ok {
		_spec.SetField(image.FieldUUID, field.TypeString, value)
	}
	if value, ok := iu.mutation.URL(); ok {
		_spec.SetField(image.FieldURL, field.TypeString, value)
	}
	if iu.mutation.URLCleared() {
		_spec.ClearField(image.FieldURL, field.TypeString)
	}
	if value, ok := iu.mutation.ObjectID(); ok {
		_spec.SetField(image.FieldObjectID, field.TypeString, value)
	}
	if iu.mutation.ObjectIDCleared() {
		_spec.ClearField(image.FieldObjectID, field.TypeString)
	}
	if value, ok := iu.mutation.TmpURL(); ok {
		_spec.SetField(image.FieldTmpURL, field.TypeString, value)
	}
	if value, ok := iu.mutation.Service(); ok {
		_spec.SetField(image.FieldService, field.TypeString, value)
	}
	if iu.mutation.ServiceCleared() {
		_spec.ClearField(image.FieldService, field.TypeString)
	}
	if value, ok := iu.mutation.GetType(); ok {
		_spec.SetField(image.FieldType, field.TypeString, value)
	}
	if iu.mutation.TypeCleared() {
		_spec.ClearField(image.FieldType, field.TypeString)
	}
	if value, ok := iu.mutation.IsProceed(); ok {
		_spec.SetField(image.FieldIsProceed, field.TypeBool, value)
	}
	if value, ok := iu.mutation.IsDeleted(); ok {
		_spec.SetField(image.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := iu.mutation.ContentType(); ok {
		_spec.SetField(image.FieldContentType, field.TypeString, value)
	}
	if value, ok := iu.mutation.Size(); ok {
		_spec.SetField(image.FieldSize, field.TypeJSON, value)
	}
	if iu.mutation.SizeCleared() {
		_spec.ClearField(image.FieldSize, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// ImageUpdateOne is the builder for updating a single Image entity.
type ImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageMutation
}

// SetUpdateTime sets the "update_time" field.
func (iuo *ImageUpdateOne) SetUpdateTime(t time.Time) *ImageUpdateOne {
	iuo.mutation.SetUpdateTime(t)
	return iuo
}

// SetUUID sets the "uuid" field.
func (iuo *ImageUpdateOne) SetUUID(s string) *ImageUpdateOne {
	iuo.mutation.SetUUID(s)
	return iuo
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableUUID(s *string) *ImageUpdateOne {
	if s != nil {
		iuo.SetUUID(*s)
	}
	return iuo
}

// SetURL sets the "url" field.
func (iuo *ImageUpdateOne) SetURL(s string) *ImageUpdateOne {
	iuo.mutation.SetURL(s)
	return iuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableURL(s *string) *ImageUpdateOne {
	if s != nil {
		iuo.SetURL(*s)
	}
	return iuo
}

// ClearURL clears the value of the "url" field.
func (iuo *ImageUpdateOne) ClearURL() *ImageUpdateOne {
	iuo.mutation.ClearURL()
	return iuo
}

// SetObjectID sets the "object_id" field.
func (iuo *ImageUpdateOne) SetObjectID(s string) *ImageUpdateOne {
	iuo.mutation.SetObjectID(s)
	return iuo
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableObjectID(s *string) *ImageUpdateOne {
	if s != nil {
		iuo.SetObjectID(*s)
	}
	return iuo
}

// ClearObjectID clears the value of the "object_id" field.
func (iuo *ImageUpdateOne) ClearObjectID() *ImageUpdateOne {
	iuo.mutation.ClearObjectID()
	return iuo
}

// SetTmpURL sets the "tmp_url" field.
func (iuo *ImageUpdateOne) SetTmpURL(s string) *ImageUpdateOne {
	iuo.mutation.SetTmpURL(s)
	return iuo
}

// SetNillableTmpURL sets the "tmp_url" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableTmpURL(s *string) *ImageUpdateOne {
	if s != nil {
		iuo.SetTmpURL(*s)
	}
	return iuo
}

// SetService sets the "service" field.
func (iuo *ImageUpdateOne) SetService(s string) *ImageUpdateOne {
	iuo.mutation.SetService(s)
	return iuo
}

// SetNillableService sets the "service" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableService(s *string) *ImageUpdateOne {
	if s != nil {
		iuo.SetService(*s)
	}
	return iuo
}

// ClearService clears the value of the "service" field.
func (iuo *ImageUpdateOne) ClearService() *ImageUpdateOne {
	iuo.mutation.ClearService()
	return iuo
}

// SetType sets the "type" field.
func (iuo *ImageUpdateOne) SetType(s string) *ImageUpdateOne {
	iuo.mutation.SetType(s)
	return iuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableType(s *string) *ImageUpdateOne {
	if s != nil {
		iuo.SetType(*s)
	}
	return iuo
}

// ClearType clears the value of the "type" field.
func (iuo *ImageUpdateOne) ClearType() *ImageUpdateOne {
	iuo.mutation.ClearType()
	return iuo
}

// SetIsProceed sets the "is_proceed" field.
func (iuo *ImageUpdateOne) SetIsProceed(b bool) *ImageUpdateOne {
	iuo.mutation.SetIsProceed(b)
	return iuo
}

// SetNillableIsProceed sets the "is_proceed" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableIsProceed(b *bool) *ImageUpdateOne {
	if b != nil {
		iuo.SetIsProceed(*b)
	}
	return iuo
}

// SetIsDeleted sets the "is_deleted" field.
func (iuo *ImageUpdateOne) SetIsDeleted(b bool) *ImageUpdateOne {
	iuo.mutation.SetIsDeleted(b)
	return iuo
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableIsDeleted(b *bool) *ImageUpdateOne {
	if b != nil {
		iuo.SetIsDeleted(*b)
	}
	return iuo
}

// SetContentType sets the "content_type" field.
func (iuo *ImageUpdateOne) SetContentType(s string) *ImageUpdateOne {
	iuo.mutation.SetContentType(s)
	return iuo
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableContentType(s *string) *ImageUpdateOne {
	if s != nil {
		iuo.SetContentType(*s)
	}
	return iuo
}

// SetSize sets the "size" field.
func (iuo *ImageUpdateOne) SetSize(pr processor.Size) *ImageUpdateOne {
	iuo.mutation.SetSize(pr)
	return iuo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableSize(pr *processor.Size) *ImageUpdateOne {
	if pr != nil {
		iuo.SetSize(*pr)
	}
	return iuo
}

// ClearSize clears the value of the "size" field.
func (iuo *ImageUpdateOne) ClearSize() *ImageUpdateOne {
	iuo.mutation.ClearSize()
	return iuo
}

// Mutation returns the ImageMutation object of the builder.
func (iuo *ImageUpdateOne) Mutation() *ImageMutation {
	return iuo.mutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (iuo *ImageUpdateOne) Where(ps ...predicate.Image) *ImageUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *ImageUpdateOne) Select(field string, fields ...string) *ImageUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Image entity.
func (iuo *ImageUpdateOne) Save(ctx context.Context) (*Image, error) {
	iuo.defaults()
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *ImageUpdateOne) SaveX(ctx context.Context) *Image {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *ImageUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *ImageUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iuo *ImageUpdateOne) defaults() {
	if _, ok := iuo.mutation.UpdateTime(); !ok {
		v := image.UpdateDefaultUpdateTime()
		iuo.mutation.SetUpdateTime(v)
	}
}

func (iuo *ImageUpdateOne) sqlSave(ctx context.Context) (_node *Image, err error) {
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Image.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, image.FieldID)
		for _, f := range fields {
			if !image.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != image.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.UpdateTime(); ok {
		_spec.SetField(image.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := iuo.mutation.UUID(); ok {
		_spec.SetField(image.FieldUUID, field.TypeString, value)
	}
	if value, ok := iuo.mutation.URL(); ok {
		_spec.SetField(image.FieldURL, field.TypeString, value)
	}
	if iuo.mutation.URLCleared() {
		_spec.ClearField(image.FieldURL, field.TypeString)
	}
	if value, ok := iuo.mutation.ObjectID(); ok {
		_spec.SetField(image.FieldObjectID, field.TypeString, value)
	}
	if iuo.mutation.ObjectIDCleared() {
		_spec.ClearField(image.FieldObjectID, field.TypeString)
	}
	if value, ok := iuo.mutation.TmpURL(); ok {
		_spec.SetField(image.FieldTmpURL, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Service(); ok {
		_spec.SetField(image.FieldService, field.TypeString, value)
	}
	if iuo.mutation.ServiceCleared() {
		_spec.ClearField(image.FieldService, field.TypeString)
	}
	if value, ok := iuo.mutation.GetType(); ok {
		_spec.SetField(image.FieldType, field.TypeString, value)
	}
	if iuo.mutation.TypeCleared() {
		_spec.ClearField(image.FieldType, field.TypeString)
	}
	if value, ok := iuo.mutation.IsProceed(); ok {
		_spec.SetField(image.FieldIsProceed, field.TypeBool, value)
	}
	if value, ok := iuo.mutation.IsDeleted(); ok {
		_spec.SetField(image.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := iuo.mutation.ContentType(); ok {
		_spec.SetField(image.FieldContentType, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Size(); ok {
		_spec.SetField(image.FieldSize, field.TypeJSON, value)
	}
	if iuo.mutation.SizeCleared() {
		_spec.ClearField(image.FieldSize, field.TypeJSON)
	}
	_node = &Image{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
