// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.smartbet.am/golang/smart-image/ent/image"
	"gitlab.smartbet.am/golang/smart-image/internal/service/processor"
)

// ImageCreate is the builder for creating a Image entity.
type ImageCreate struct {
	config
	mutation *ImageMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (ic *ImageCreate) SetCreateTime(t time.Time) *ImageCreate {
	ic.mutation.SetCreateTime(t)
	return ic
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ic *ImageCreate) SetNillableCreateTime(t *time.Time) *ImageCreate {
	if t != nil {
		ic.SetCreateTime(*t)
	}
	return ic
}

// SetUpdateTime sets the "update_time" field.
func (ic *ImageCreate) SetUpdateTime(t time.Time) *ImageCreate {
	ic.mutation.SetUpdateTime(t)
	return ic
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ic *ImageCreate) SetNillableUpdateTime(t *time.Time) *ImageCreate {
	if t != nil {
		ic.SetUpdateTime(*t)
	}
	return ic
}

// SetUUID sets the "uuid" field.
func (ic *ImageCreate) SetUUID(s string) *ImageCreate {
	ic.mutation.SetUUID(s)
	return ic
}

// SetURL sets the "url" field.
func (ic *ImageCreate) SetURL(s string) *ImageCreate {
	ic.mutation.SetURL(s)
	return ic
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (ic *ImageCreate) SetNillableURL(s *string) *ImageCreate {
	if s != nil {
		ic.SetURL(*s)
	}
	return ic
}

// SetObjectID sets the "object_id" field.
func (ic *ImageCreate) SetObjectID(s string) *ImageCreate {
	ic.mutation.SetObjectID(s)
	return ic
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (ic *ImageCreate) SetNillableObjectID(s *string) *ImageCreate {
	if s != nil {
		ic.SetObjectID(*s)
	}
	return ic
}

// SetTmpURL sets the "tmp_url" field.
func (ic *ImageCreate) SetTmpURL(s string) *ImageCreate {
	ic.mutation.SetTmpURL(s)
	return ic
}

// SetService sets the "service" field.
func (ic *ImageCreate) SetService(s string) *ImageCreate {
	ic.mutation.SetService(s)
	return ic
}

// SetNillableService sets the "service" field if the given value is not nil.
func (ic *ImageCreate) SetNillableService(s *string) *ImageCreate {
	if s != nil {
		ic.SetService(*s)
	}
	return ic
}

// SetType sets the "type" field.
func (ic *ImageCreate) SetType(s string) *ImageCreate {
	ic.mutation.SetType(s)
	return ic
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ic *ImageCreate) SetNillableType(s *string) *ImageCreate {
	if s != nil {
		ic.SetType(*s)
	}
	return ic
}

// SetIsProceed sets the "is_proceed" field.
func (ic *ImageCreate) SetIsProceed(b bool) *ImageCreate {
	ic.mutation.SetIsProceed(b)
	return ic
}

// SetNillableIsProceed sets the "is_proceed" field if the given value is not nil.
func (ic *ImageCreate) SetNillableIsProceed(b *bool) *ImageCreate {
	if b != nil {
		ic.SetIsProceed(*b)
	}
	return ic
}

// SetIsDeleted sets the "is_deleted" field.
func (ic *ImageCreate) SetIsDeleted(b bool) *ImageCreate {
	ic.mutation.SetIsDeleted(b)
	return ic
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (ic *ImageCreate) SetNillableIsDeleted(b *bool) *ImageCreate {
	if b != nil {
		ic.SetIsDeleted(*b)
	}
	return ic
}

// SetContentType sets the "content_type" field.
func (ic *ImageCreate) SetContentType(s string) *ImageCreate {
	ic.mutation.SetContentType(s)
	return ic
}

// SetSize sets the "size" field.
func (ic *ImageCreate) SetSize(pr processor.Size) *ImageCreate {
	ic.mutation.SetSize(pr)
	return ic
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (ic *ImageCreate) SetNillableSize(pr *processor.Size) *ImageCreate {
	if pr != nil {
		ic.SetSize(*pr)
	}
	return ic
}

// Mutation returns the ImageMutation object of the builder.
func (ic *ImageCreate) Mutation() *ImageMutation {
	return ic.mutation
}

// Save creates the Image in the database.
func (ic *ImageCreate) Save(ctx context.Context) (*Image, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *ImageCreate) SaveX(ctx context.Context) *Image {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *ImageCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *ImageCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *ImageCreate) defaults() {
	if _, ok := ic.mutation.CreateTime(); !ok {
		v := image.DefaultCreateTime()
		ic.mutation.SetCreateTime(v)
	}
	if _, ok := ic.mutation.UpdateTime(); !ok {
		v := image.DefaultUpdateTime()
		ic.mutation.SetUpdateTime(v)
	}
	if _, ok := ic.mutation.IsProceed(); !ok {
		v := image.DefaultIsProceed
		ic.mutation.SetIsProceed(v)
	}
	if _, ok := ic.mutation.IsDeleted(); !ok {
		v := image.DefaultIsDeleted
		ic.mutation.SetIsDeleted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *ImageCreate) check() error {
	if _, ok := ic.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Image.create_time"`)}
	}
	if _, ok := ic.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Image.update_time"`)}
	}
	if _, ok := ic.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "Image.uuid"`)}
	}
	if _, ok := ic.mutation.TmpURL(); !ok {
		return &ValidationError{Name: "tmp_url", err: errors.New(`ent: missing required field "Image.tmp_url"`)}
	}
	if _, ok := ic.mutation.IsProceed(); !ok {
		return &ValidationError{Name: "is_proceed", err: errors.New(`ent: missing required field "Image.is_proceed"`)}
	}
	if _, ok := ic.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "Image.is_deleted"`)}
	}
	if _, ok := ic.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "Image.content_type"`)}
	}
	return nil
}

func (ic *ImageCreate) sqlSave(ctx context.Context) (*Image, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *ImageCreate) createSpec() (*Image, *sqlgraph.CreateSpec) {
	var (
		_node = &Image{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(image.Table, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt))
	)
	if value, ok := ic.mutation.CreateTime(); ok {
		_spec.SetField(image.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := ic.mutation.UpdateTime(); ok {
		_spec.SetField(image.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := ic.mutation.UUID(); ok {
		_spec.SetField(image.FieldUUID, field.TypeString, value)
		_node.UUID = value
	}
	if value, ok := ic.mutation.URL(); ok {
		_spec.SetField(image.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := ic.mutation.ObjectID(); ok {
		_spec.SetField(image.FieldObjectID, field.TypeString, value)
		_node.ObjectID = value
	}
	if value, ok := ic.mutation.TmpURL(); ok {
		_spec.SetField(image.FieldTmpURL, field.TypeString, value)
		_node.TmpURL = value
	}
	if value, ok := ic.mutation.Service(); ok {
		_spec.SetField(image.FieldService, field.TypeString, value)
		_node.Service = value
	}
	if value, ok := ic.mutation.GetType(); ok {
		_spec.SetField(image.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := ic.mutation.IsProceed(); ok {
		_spec.SetField(image.FieldIsProceed, field.TypeBool, value)
		_node.IsProceed = value
	}
	if value, ok := ic.mutation.IsDeleted(); ok {
		_spec.SetField(image.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if value, ok := ic.mutation.ContentType(); ok {
		_spec.SetField(image.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := ic.mutation.Size(); ok {
		_spec.SetField(image.FieldSize, field.TypeJSON, value)
		_node.Size = value
	}
	return _node, _spec
}

// ImageCreateBulk is the builder for creating many Image entities in bulk.
type ImageCreateBulk struct {
	config
	err      error
	builders []*ImageCreate
}

// Save creates the Image entities in the database.
func (icb *ImageCreateBulk) Save(ctx context.Context) ([]*Image, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Image, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *ImageCreateBulk) SaveX(ctx context.Context) []*Image {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *ImageCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *ImageCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
