// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gitlab.smartbet.am/golang/smart-image/ent/image"
	"gitlab.smartbet.am/golang/smart-image/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescIsProceed is the schema descriptor for is_proceed field.
	imageDescIsProceed := imageFields[6].Descriptor()
	// image.DefaultIsProceed holds the default value on creation for the is_proceed field.
	image.DefaultIsProceed = imageDescIsProceed.Default.(bool)
	// imageDescIsDeleted is the schema descriptor for is_deleted field.
	imageDescIsDeleted := imageFields[7].Descriptor()
	// image.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	image.DefaultIsDeleted = imageDescIsDeleted.Default.(bool)
}
