name: Docker Image CI
run-name: Deploy to ${{ inputs.env || 'dev' }} by @${{ github.actor }}

on:
  push:
    paths-ignore:
      - .github/workflows/*.yaml

  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to promote to'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - test
          - stage
      tag:
        description: "Tag to deploy"
        required: false
        type: string
        default: ""


env:
  environment: ${{ github.event.inputs.env || 'dev' }}
  tag: ${{ github.event.inputs.tag || '' }}

jobs:

  build-image:
    uses: Phoenix365-tech/actions/.github/workflows/docker-build.yaml@main
    with:
      image_tag: ${{ inputs.tag }}

  set-env:
    runs-on: infra-runner
    outputs:
      deploy_environment: ${{ steps.setup-env.outputs.deploy_environment }}
    steps:
      - name: Set up environment variable
        id: setup-env
        run: |
          ENVIRONMENT="${{ github.event.inputs.env || 'dev' }}"
          echo "deploy_environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

  deploy:
    needs: [build-image, set-env]
    uses: Phoenix365-tech/actions/.github/workflows/deploy.yaml@main
    with:
      env: ${{ needs.set-env.outputs.deploy_environment }}
      image_tag: ${{ needs.build-image.outputs.image_tag }}
    secrets:
      token: ${{ secrets.PHOENIX_ORG_TOKEN }}
